kind: PersistentVolume
apiVersion: v1
metadata:
  name: pvrabbit
  labels:
    type: local
spec:
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/bitnami/rabbitmq"
