apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: [ "/bin/sh","-c","ls -al . ; ls -al server; cat server/config.json; echo 'Environment:' {{ .Release.Namespace }}; node ." ]
          env:
          - name: NODE_ENV
            value: {{ .Release.Namespace }}
          ports:
            - containerPort: {{ .Values.service.internalPort }}
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.internalPort }}
            initialDelaySeconds: 30
            timeoutSeconds: 30
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 10
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.internalPort }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
          volumeMounts:
            - name: config-volume
              mountPath: /usr/src/app/server/config.local.js
              subPath: config.local.js
            - name: config-volume
              mountPath: /usr/src/app/server/component-config.{{ .Release.Namespace }}.json
              subPath: component-config.json
            - name: config-volume
              mountPath: /usr/src/app/server/middleware.{{ .Release.Namespace }}.json
              subPath: middleware.json
            - name: config-volume
              mountPath: /usr/src/app/server/providers.local.json
              subPath: providers.json
            - name: config-volume
              mountPath: /usr/src/app/server/providers.json
              subPath: providers.json
            - name: config-volume
              mountPath: /usr/src/app/server/datasources.{{ .Release.Namespace }}.json
              subPath: datasources.json
            - name: config-volume
              mountPath: /usr/src/app/server/datasources.json
              subPath: datasources.json
      volumes:
        - name: config-volume
          configMap:
            name: {{ template "fullname" . }}
    {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
    {{- end }}
